### ISSUE TITLE
AttributeError: module 'octobot_trading.modes.script_keywords' has no attribute 'get_price_with_offset'

### ISSUE THREAD

**Issue by jechaviz** [Drakkar-Software/OctoBot-Pro#38]
Just installed under Python 3.10.1 on Windows 10 Machine.
Following instructions on:
https://www.octobot.cloud/en/guides/octobot-script#the-script-based-trading-framework-using-octobot
I ran the sample script there, then I get next error:
**AttributeError: module 'octobot_trading.modes.script_keywords' has no attribute 'get_price_with_offset'**
Complete Log:
```
C:\Users\jesus\.pyenv\pyenv-win\versions\3.10.1\python.exe "C:\git\octobot-scripts\rsi strategy sample.py" 
2024-05-01 10:20:07,327:INFO - Failed to load SSL library: <class 'OSError'> (no library called "ssl" found)
2024-05-01 10:20:07,329:INFO - cryptg module not installed and libssl not found, falling back to (slower) Python encryption
2024-05-01 10:20:08,852:ERROR - configuration issue: missing login information !
2024-05-01 10:20:13,696:INFO - Start collecting history on binance
2024-05-01 10:20:13,696:INFO - Collecting history for BTC/USDT...
2024-05-01 10:20:13,696:INFO - [0/1] Collecting BTC/USDT history on TimeFrames.ONE_DAY...
2024-05-01 10:20:14,846:INFO - [20.6310819404537%] historical data fetched for BTC/USDT TimeFrames.ONE_DAY
2024-05-01 10:20:15,552:INFO - [41.30350873449548%] historical data fetched for BTC/USDT TimeFrames.ONE_DAY
2024-05-01 10:20:15,825:INFO - [61.97593552853726%] historical data fetched for BTC/USDT TimeFrames.ONE_DAY
2024-05-01 10:20:16,504:INFO - [82.64836232257905%] historical data fetched for BTC/USDT TimeFrames.ONE_DAY
2024-05-01 10:20:16,767:INFO - [99.97185597598606%] historical data fetched for BTC/USDT TimeFrames.ONE_DAY
2024-05-01 10:20:16,830:INFO - Loaded binance data file with BTC/USDT on 1d
2024-05-01 10:20:16,986:ERROR - module 'octobot_trading.modes.script_keywords' has no attribute 'get_price_with_offset'
Traceback (most recent call last):
  File "C:\Users\jesus\.pyenv\pyenv-win\versions\3.10.1\lib\site-packages\octobot_trading\modes\scripted_trading_mode\abstract_scripted_trading_mode.py", line 270, in call_script
    await self.trading_mode.get_script(live=True)(context)
  File "C:\git\octobot-scripts\rsi strategy sample.py", line 27, in strategy
    await obs.market(ctx, "buy", amount="10%", stop_loss_offset="-15%", take_profit_offset="25%")
  File "C:\Users\jesus\AppData\Local\Drakkar-Software\OctoBot-Script\0.0.16\imports\tentacles\Meta\Keywords\scripting_library\orders\order_types\market_order.py", line 44, in market
    return await create_order.create_order_instance(
  File "C:\Users\jesus\AppData\Local\Drakkar-Software\OctoBot-Script\0.0.16\imports\tentacles\Meta\Keywords\scripting_library\orders\order_types\create_order.py", line 78, in create_order_instance
    await _get_order_details(context, order_type_name, side, order_offset, reduce_only, order_limit_offset)
  File "C:\Users\jesus\AppData\Local\Drakkar-Software\OctoBot-Script\0.0.16\imports\tentacles\Meta\Keywords\scripting_library\orders\order_types\create_order.py", line 193, in _get_order_details
    order_price = await script_keywords.get_price_with_offset(context, "0")
AttributeError: module 'octobot_trading.modes.script_keywords' has no attribute 'get_price_with_offset'
2024-05-01 10:20:17,025:ERROR - Error when running script: module 'octobot_trading.modes.script_keywords' has no attribute 'get_price_with_offset' (error: AttributeError)
2024-05-01 10:20:17,026:ERROR - module 'octobot_trading.modes.script_keywords' has no attribute 'get_price_with_offset'
Traceback (most recent call last):
  File "C:\Users\jesus\.pyenv\pyenv-win\versions\3.10.1\lib\site-packages\octobot_trading\modes\scripted_trading_mode\abstract_scripted_trading_mode.py", line 270, in call_script
    await self.trading_mode.get_script(live=True)(context)
  File "C:\git\octobot-scripts\rsi strategy sample.py", line 27, in strategy
    await obs.market(ctx, "buy", amount="10%", stop_loss_offset="-15%", take_profit_offset="25%")
  File "C:\Users\jesus\AppData\Local\Drakkar-Software\OctoBot-Script\0.0.16\imports\tentacles\Meta\Keywords\scripting_library\orders\order_types\market_order.py", line 44, in market
    return await create_order.create_order_instance(
  File "C:\Users\jesus\AppData\Local\Drakkar-Software\OctoBot-Script\0.0.16\imports\tentacles\Meta\Keywords\scripting_library\orders\order_types\create_order.py", line 78, in create_order_instance
    await _get_order_details(context, order_type_name, side, order_offset, reduce_only, order_limit_offset)
  File "C:\Users\jesus\AppData\Local\Drakkar-Software\OctoBot-Script\0.0.16\imports\tentacles\Meta\Keywords\scripting_library\orders\order_types\create_order.py", line 193, in _get_order_details
    order_price = await script_keywords.get_price_with_offset(context, "0")
AttributeError: module 'octobot_trading.modes.script_keywords' has no attribute 'get_price_with_offset'
2024-05-01 10:20:17,030:ERROR - Error when running script: module 'octobot_trading.modes.script_keywords' has no attribute 'get_price_with_offset' (error: AttributeError)
... And so on for each tried order...
[2.01s / 2419 candles] profitability: {'binance': 0.0} market average: {'binance': 1442.88930510623} strategy_config: {'period': 10, 'rsi_value_buy_threshold': 28}
Report in user\data\BacktesterTradingMode\default_campaign\backtesting\backtesting_4\report.html

Process finished with exit code 0
```

**Comment by GuillaumeDSM** [comment]
Hey @jechaviz !
Thanks for reporting the issue. Can you try to update OctoBot Script to 0.0.17 and try again please ?

**Comment by jechaviz** [comment]
worked: python pip install --force-reinstall -v "octobot-script==0.0.17"

**Comment by jechaviz** [comment]
Thank you so much
